server.port: 8090
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: datatype-restBD
  datasource:
    url: jdbc:postgresql://localhost:5432/DataTypeRestBD
    username: postgres
    password: postgres
    driver-class-name: "org.postgresql.Driver"

  flyway:
    enabled: true
    baselineOnMigrate: true
    baselineVersion: 000
    schemas: public